# Generated by Django 5.1.3 on 2024-12-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analysis_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="netflixcontent",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
